// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePirates.API.Data;

#nullable disable

namespace SpacePirates.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502202731_AddShipEntity")]
    partial class AddShipEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpacePirates.API.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("CurrentCargoLoad")
                        .HasColumnType("int");

                    b.Property<int>("CurrentFuel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHullIntegrity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentShieldCapacity")
                        .HasColumnType("int");

                    b.Property<int>("DefenseLevel")
                        .HasColumnType("int");

                    b.Property<int>("EngineLevel")
                        .HasColumnType("int");

                    b.Property<double>("FuelEfficiency")
                        .HasColumnType("double");

                    b.Property<bool>("IsInCombat")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastDocked")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Maneuverability")
                        .HasColumnType("double");

                    b.Property<int>("MaxCargoCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MaxFuelCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MaxHullIntegrity")
                        .HasColumnType("int");

                    b.Property<int>("MaxShieldCapacity")
                        .HasColumnType("int");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WeaponLevel")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
