// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePirates.API.Data;

#nullable disable

namespace SpacePirates.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505230823_AddGalaxyAndShipModels")]
    partial class AddGalaxyAndShipModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpacePirates.API.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("SpacePirates.API.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<bool>("IsInCombat")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastDocked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.CargoSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("CargoSystems");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.FuelSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CurrentFuel")
                        .HasColumnType("double");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("FuelSystems");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Hull", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentIntegrity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Hulls");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Shield", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Charging")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CurrentIntegrity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastRechargeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Shields");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.WeaponSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpgraded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("WeaponSystems");
                });

            modelBuilder.Entity("SpacePirates.API.Models.Position", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("Position")
                        .HasForeignKey("SpacePirates.API.Models.Position", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.CargoSystem", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("CargoSystem")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.CargoSystem", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Engine", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("Engine")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.Engine", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.FuelSystem", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("FuelSystem")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.FuelSystem", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Hull", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("Hull")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.Hull", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.Shield", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("Shield")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.Shield", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.ShipComponents.WeaponSystem", b =>
                {
                    b.HasOne("SpacePirates.API.Models.Ship", "Ship")
                        .WithOne("WeaponSystem")
                        .HasForeignKey("SpacePirates.API.Models.ShipComponents.WeaponSystem", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SpacePirates.API.Models.Ship", b =>
                {
                    b.Navigation("CargoSystem")
                        .IsRequired();

                    b.Navigation("Engine")
                        .IsRequired();

                    b.Navigation("FuelSystem")
                        .IsRequired();

                    b.Navigation("Hull")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Shield")
                        .IsRequired();

                    b.Navigation("WeaponSystem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
